---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: uat-namespace
spec:
  # replicas: 4
  selector:
    matchLabels:
      app: tms-backend
  template:
    metadata:
      labels:
        app: tms-backend
    spec:
      imagePullSecrets:
      - name: harbor-backend-credentials
      containers:
      - name: tms-backend
        image: 10.0.200.204:7200/trainee/backend:0.1.86-dev
        imagePullPolicy: Always
#        envFrom:
#          - configMapRef:
#              name: my-configmap

#        resources:
 #         limits:
  #          memory: "128Mi"
   #         cpu: "500m"
        ports:
        - containerPort: 8080
      nodeName: apduatsvmtsap01
