apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: uat-namespace
spec:
  type: NodePort
  externalIPs:
  - 10.0.218.158
  selector:
    app: tms-backend
  ports:
    - port: 8080
      # By default and for convenience, the targetPort is set to
      # the same value as the port field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30002
      protocol: TCP
status:
  loadBalancer: {}
